### ISSUE TITLE
readme points to incorrect location

### ISSUE THREAD

**Issue by vadixidav** [indianajohn/akaze-rust#5]
The `readme` field in the `Cargo.toml` needs to point to `../README.md`. This was broken when I changed to a workspace in #4.

**Comment by vadixidav** [comment]
I notice the readme was moved to the akaze directory. I think we should move it back up a directory so it is visible on github again, but then change the readme path appropriately.

**Comment by indianajohn** [comment]
How do you feel about just linking to the main README? Look at `master` in my repository.

**Comment by indianajohn** [comment]
Actually, I like your suggestion better. Stand by.

**Comment by vadixidav** [comment]
I see how you have separated out the util readme from the library. I think this makes more sense than combining everything. I thought it was broken, but it looks good 👍. Thank you for making sure that was set up correctly.

**Comment by vadixidav** [comment]
Oh, feel free to reopen the issue if you like. I commented before I saw your comment.
